Repository tskit-dev/tskit, pull requests merged in 2022-07, with the labels that each got.

#2366 Add migrations argument to load_text and dump_text
  docs/python-api.md
  python/tests/test_highlevel.py
  python/tests/test_metadata.py
  python/tskit/text_formats.py
  python/tskit/trees.py
Labels: enhancement, AUTOMERGE-REQUESTED, Python API

#2369 Add migrations subcommand
  python/tests/test_cli.py
  python/tskit/cli.py
Labels: enhancement, AUTOMERGE-REQUESTED, Python API

#2379 Fix bugs in test_empty_files and test_empty_files_sequence_length
  python/tests/test_highlevel.py
Labels: bug, AUTOMERGE-REQUESTED, Python API

#2386 Remove _node_edges and _tree_node_edges
  python/tskit/trees.py
Labels: AUTOMERGE-REQUESTED

#2388 Simplify sort doc text
  python/tskit/tables.py
Labels: AUTOMERGE-REQUESTED

#2391 Clarify the set_columns behaviour for schemas
  python/tskit/tables.py
Labels: AUTOMERGE-REQUESTED

#2385 Add site.alleles method
  python/CHANGELOG.rst
  python/tests/test_highlevel.py
  python/tskit/trees.py
Labels: AUTOMERGE-REQUESTED

#2389 Add table.replace_with
  python/CHANGELOG.rst
  python/tests/test_tables.py
  python/tskit/tables.py
Labels: AUTOMERGE-REQUESTED

#2397 Allow haplotypes and alignments to have left, right, samples params
  python/CHANGELOG.rst
  python/tests/test_genotypes.py
  python/tskit/trees.py
Labels: AUTOMERGE-REQUESTED

#2396 Clarify "canonical" in docs
  python/tskit/tables.py
Labels: AUTOMERGE-REQUESTED

#2392 Make the returned rank a namedtuple
  docs/python-api.md
  python/tests/test_combinatorics.py
  python/tskit/__init__.py
  python/tskit/combinatorics.py
  python/tskit/trees.py
Labels: AUTOMERGE-REQUESTED

#2405 Correct some docstrings and return types
  python/tskit/genotypes.py
Labels: AUTOMERGE-REQUESTED

#2407 Hive off definitions into a glossary
  docs/_toc.yml
  docs/data-model.md
  docs/glossary.md
Labels: AUTOMERGE-REQUESTED

#2409 Check that both trees and tree seqs can plot integer times
  python/tests/test_drawing.py
  python/tskit/drawing.py
Labels: AUTOMERGE-REQUESTED

#2413 Post release tasks
  c/CHANGELOG.rst
  python/CHANGELOG.rst
  python/tskit/_version.py
Labels: AUTOMERGE-REQUESTED

#2415 Simplify table.replace_with
  python/tests/test_tables.py
  python/tskit/tables.py
Labels: AUTOMERGE-REQUESTED

#2404 Rephrase the Variant docs a little
  python/tskit/genotypes.py
Labels: AUTOMERGE-REQUESTED

#2414 special case start and end when we want all the variants()
  python/tskit/trees.py
Labels: AUTOMERGE-REQUESTED

#2412 Minor reading tweaks to quickstart
  docs/quickstart.md
Labels: AUTOMERGE-REQUESTED

#2393 Implement allele counting methods
  python/CHANGELOG.rst
  python/tests/conftest.py
  python/tests/test_genotypes.py
  python/tskit/genotypes.py
Labels: AUTOMERGE-REQUESTED

#2425 tweak to bincount
  python/tskit/genotypes.py
Labels: AUTOMERGE-REQUESTED

#2422 Tree num lineages
  c/tests/test_trees.c
  c/tskit/trees.c
  c/tskit/trees.h
  python/CHANGELOG.rst
  python/_tskitmodule.c
  python/tests/test_highlevel.py
  python/tests/test_lowlevel.py
  python/tskit/trees.py
Labels: AUTOMERGE-REQUESTED

#2439 Fix memory leak in table references.
  python/tskit/tables.py
Labels: AUTOMERGE-REQUESTED

#2437 Fix segfault in tsk_variant_restricted_copy
  c/CHANGELOG.rst
  c/tests/test_genotypes.c
  c/tskit/genotypes.c
  python/CHANGELOG.rst
  python/tests/test_lowlevel.py
Labels: AUTOMERGE-REQUESTED

#2441 Cache table refs
  python/CHANGELOG.rst
  python/tskit/tables.py
  python/tskit/trees.py
Labels: AUTOMERGE-REQUESTED

#2384 Add __str__ and _repr_html_ to Variant
  python/tests/test_genotypes.py
  python/tskit/genotypes.py
  python/tskit/util.py
Labels: enhancement, AUTOMERGE-REQUESTED, Python API

#2450 Release prep
  c/CHANGELOG.rst
  c/VERSION.txt
  c/tskit/core.h
  docs/development.md
  python/CHANGELOG.rst
  python/tests/test_lowlevel.py
  python/tskit/_version.py
Labels: AUTOMERGE-REQUESTED
