Repository tskit-dev/tskit, pull requests merged in 2022-06, with the labels that each got.

#2306 Refactor ``Variant`` class and associated genotype utility functions
  python/tests/test_genotypes.py
  python/tests/test_util.py
  python/tskit/__init__.py
  python/tskit/genotypes.py
  python/tskit/trees.py
  python/tskit/util.py
Labels: AUTOMERGE-REQUESTED, Python API, Infrastructure and tools, refactoring

#2314 Fix individuals text output
  c/tskit/tables.c
Labels: AUTOMERGE-REQUESTED

#2316 Add num_children C level
  c/CHANGELOG.rst
  c/tests/test_trees.c
  c/tskit/trees.c
  c/tskit/trees.h
  python/tests/__init__.py
  python/tests/test_utilities.py
  python/tests/tsutil.py
Labels: AUTOMERGE-REQUESTED

#2300 VCF masking
  python/CHANGELOG.rst
  python/tests/test_vcf.py
  python/tskit/trees.py
  python/tskit/vcf.py
Labels: enhancement, AUTOMERGE-REQUESTED, Python API

#2326 Finish Variant Class
  python/_tskitmodule.c
  python/tests/test_genotypes.py
  python/tests/test_lowlevel.py
  python/tskit/genotypes.py
Labels: AUTOMERGE-REQUESTED

#2302 Delete_older operation
  c/tests/test_tables.c
  c/tskit/tables.c
  c/tskit/tables.h
  python/_tskitmodule.c
  python/tests/test_lowlevel.py
  python/tests/test_table_transforms.py
  python/tskit/tables.py
Labels: AUTOMERGE-REQUESTED

#2331 Decapitate2
  docs/python-api.md
  python/CHANGELOG.rst
  python/tests/test_table_transforms.py
  python/tskit/tables.py
  python/tskit/trees.py
Labels: AUTOMERGE-REQUESTED

#2337 Limit table size to TSK_MAX_ID
  c/CHANGELOG.rst
  c/tests/test_tables.c
  c/tskit/tables.c
Labels: AUTOMERGE-REQUESTED

#2343 Add specific error for no sample lists
  python/_tskitmodule.c
  python/tests/test_lowlevel.py
Labels: AUTOMERGE-REQUESTED

#2348 Simplify population semantics in split_edges
  c/tests/test_trees.c
  c/tskit/trees.c
  c/tskit/trees.h
  python/_tskitmodule.c
  python/tests/test_lowlevel.py
  python/tests/test_table_transforms.py
  python/tskit/trees.py
Labels: AUTOMERGE-REQUESTED

#2351 Don't print empty byte strings for no metadata
  python/CHANGELOG.rst
  python/tests/test_tables.py
  python/tests/test_util.py
  python/tskit/tables.py
  python/tskit/util.py
Labels: AUTOMERGE-REQUESTED

#2353 Adding B2 index and tests
  python/tests/test_balance_metrics.py
  python/tskit/trees.py
Labels: AUTOMERGE-REQUESTED

#2340 c level edge id array
  c/CHANGELOG.rst
  c/tests/test_trees.c
  c/tskit/trees.c
  c/tskit/trees.h
  python/tests/__init__.py
  python/tests/test_utilities.py
  python/tests/tsutil.py
Labels: AUTOMERGE-REQUESTED

#2354 Implement B2 index in C
  c/tests/test_trees.c
  c/tskit/trees.c
  c/tskit/trees.h
  docs/python-api.md
  python/CHANGELOG.rst
  python/_tskitmodule.c
  python/tests/test_balance_metrics.py
  python/tests/test_lowlevel.py
  python/tskit/trees.py
Labels: AUTOMERGE-REQUESTED

#2358 Change type of num_children array in docstring
  python/tskit/trees.py
Labels: AUTOMERGE-REQUESTED

#2357 Edge array Python API
  docs/data-model.md
  docs/python-api.md
  python/CHANGELOG.rst
  python/_tskitmodule.c
  python/tests/test_highlevel.py
  python/tests/test_lowlevel.py
  python/tskit/drawing.py
  python/tskit/trees.py
Labels: AUTOMERGE-REQUESTED

#2364 Post release tasks
  python/CHANGELOG.rst
  python/tskit/_version.py
Labels: AUTOMERGE-REQUESTED
